# версия когда нет внешней директории для архивов приложений
version: '3.8'
services:
  backend:
    build: .
    image: retry-connection-docker
    restart: always
    ports:
      - "8081:8081"
    #extra_hosts:
    #  - "database:172.17.0.1"
    environment:
      - TZ=Europe/Podgorica
