spring:
  application:
    name: ecom_market

  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  servlet:
    context-path: /api
  port: 8081

  core_pool_size: 4
  max_pool_size: 10
  queue_capacity: 150

client:
  connection: 5
  time: 10
